[provider]
cluster = "http://127.0.0.1:8899"
wallet = "~/.config/solana/id.json"

[programs.localnet]
token_program = "7pdu5d6AMN92b6amJeYXmdivLyPWcXzYURLfm6iqpPP3"

[scripts]
test = "npx mocha tests/**/*"

[test]
startup_wait = 30