[package]
name = "hoard_program"
version = "0.1.0"
edition = "2021"

[lib]
name = "hoard_program"
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.30.1"
solana-program = "2.0.1"

[features]
default = ["no-entrypoint"]
no-entrypoint = []

[profile.release]
opt-level = "s"